### PR TITLE
Update test runner to use new example impl file pattern

### LINKED ISSUE #299: Update test runner to use the new path for example implementation
Per https://github.com/exercism/dart/pull/298, example implementations are moved from `lib/example.dart` to `.meta/lib/example.dart`. This breaks the existing test runner.

Relevant:
 - https://github.com/exercism/dart/blob/8ec254ff2c33c98850b5e35e95a63c81fb1a5bd3/test/exercises_test.dart#L69.

### PR DESCRIPTION
**Pull request by devkabiir**
Closes #299

### CODE REVIEW

**Comment by devkabiir** [comment]
@exercism/maintainers-admin

**Review by iHiD — APPROVED** [review]

**Review by ErikSchierboom — APPROVED** [review]

**Comment by devkabiir** [comment]
Finally!, Tests are passing ✨ 🥳

**Comment by iHiD** [comment]
Great work :)

**Comment by Stargator** [comment]
Great job, @devkabiir!

**Pull request merged**
