### PR TITLE
Move From Travis to Github Actions

### PR DESCRIPTION
**Pull request by davidlutta**
Closes: #264 

### Changes and Implications
Added GitHub action to carry out automated tests.

### CODE REVIEW

**Comment by Corentin-Leffy** [comment]
Looks good to me, but you should also add the stage [check_formatting](https://github.com/exercism/dart/blob/master/.travis.yml#L19) and add [some directories](https://github.com/exercism/dart/blob/master/.travis.yml#L12) to cache.

**Review by devkabiir — CHANGES_REQUESTED** [review]
Thank you for your contribution :rocket:

Apart from what @Corentin-Leffy already mentioned, everything else LGTM 👍

Haven't touched github actions in a while so I'd appreciate if anyone else has any input on this. @exercism/dart 

Is it possible to also cover #63 using github actions? Mainly not running expensive tasks when only markdown/etc files are touched.

**Comment by davidlutta** [comment]
> Looks good to me, but you should also add the stage [check_formatting](https://github.com/exercism/dart/blob/master/.travis.yml#L19) and add [some directories](https://github.com/exercism/dart/blob/master/.travis.yml#L12) to cache.
> 
> And don't forget to delete the file `.travis.yml` and change the **build badge** in the `README.md`.

Thank you for the feedback @Corentin-Leffy I'll work on it.

**Comment by davidlutta** [comment]
Hello @Corentin-Leffy,

I'm running into some issues caching some directories as I have never done it before and would like to know where I'm 
going wrong. 

This is is my code so far.
```yaml
name: Actions

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Dependencies
      uses: actions/cache@v2
      id: cache-dependencies
      with:
        path: 
          - $HOME/.pub-cache
          - .dart_tool/pub
          - .pub/
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}


    - name: Install dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: pub get

    - name: Check Stage formatting
      run: pub run bin/check_formatting.dart

    - name: Run tests
      run: pub run test
      
```
I Keep on getting this error `The workflow is not valid. .github/workflows/actions.yml (Line: 20, Col: 11): A sequence was not expected` and I'm not sure what is wrong.

**Pull request closed without merging**
