### PR TITLE
Skip non-first tests for some exercises

### PR DESCRIPTION
**Pull request by Stargator**
Addressing #28 and #30

### CODE REVIEW

**Comment by kytrinyx** [comment]
@Stargator we really need to find a couple more people who are excited about Dart and who could help review/maintain this repository.

Do you have any suggestions for where we might entice some folks to jump in?

Are there any Dart meetups where you could lead an evening pairing workshop, for example, using Exercism? 

A great format tends to be:

- pair up and have people solve an exercise of their choice
- eat, drink, and be merry
- after the break, do "show and tell" on a screen/projector. Show the code, talk about what snags people ran into, or what they learned

Or, if there are places where the Dart folks hang out online, there might be a way to ask people to help out, but this can be dicey if you just show up and start asking for help.

**Comment by petertseng** [comment]
I don't understand why I was mentioned, so I am taking no further action other than to leave this comment saying I don't understand

**Comment by petertseng** [comment]
Excuse me as a newcomer to this conversation with no context

**Comment by petertseng** [comment]
I confirm it is true I did at least one exercise.

**Comment by petertseng** [comment]
Just kidding, I can take my best guess. Here is my response to my best guess as to why I was mentioned:

It is not feasible to ask me to maintain this track.

**Comment by petertseng** [comment]
> It is not feasible to ask me to maintain this track.

What am I talking about, obviously it is feasible to **ask** me. I can only comment on the feasibility of it actually happening. Amending the sentence to read that it is not feasible **for me** to maintain this track.

**Comment by Stargator** [comment]
Thanks @petertseng that's an understand response to a best guess why you were mentioned.

I wouldn't necessarily ask you to be a maintainer, but since you have some familiarity with Dart, maybe pop in once in a while to provide input?

Regardless, I'm going to be reaching out this weekend to see if I can pique anyone's interest in contributing

**Comment by Stargator** [comment]
@kytrinyx Go ahead and merge this since it's approved?

**Comment by Stargator** [comment]
Okay, going ahead to merge this since it is approved

**Pull request merged**
