### PR TITLE
Add linting rules for errors

### PR DESCRIPTION
**Pull request by Stargator**
Revise the analysis-options.yaml file with some lint rules to prevent errors. Will be useful as the project grows.

### CODE REVIEW

**Comment by fwip** [comment]
Awesome, I'm all for more linting.

**Comment by Stargator** [comment]
@fwip Yeah, I figured we won't need the rules around style much. But figured this would be a good start.

**Comment by kabiir** [comment]
I've some suggestions.

    - empty_catches
    - empty_statements
    - avoid_empty_else
    - avoid_return_types_on_setters  /// Makes no sense to have return types on setters.
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters  /// Supports previous rule.
    - use_setters_to_change_properties
    - valid_regexps
I'm assuming this is for switch case :

    - no_duplicate_case_values

**Comment by Stargator** [comment]
I'm going to incorporate @kabiir's suggestions

**Pull request merged**
