### PR TITLE
Add fetch canonical data syncer

### PR DESCRIPTION
**Pull request by Stargator**
Adding a tool to allow contributors to fetch the newest tool for helping tracks keep their exercise-specific tests.toml files in sync with the latest canonical data in the problem-specifications repo.

### CODE REVIEW

**Review by devkabiir — APPROVED** [review]
Please also include the PowerShell version of the script for Windows Users. (https://github.com/exercism/canonical-data-syncer#use-in-your-track)
There's no need to add specific instructions for PowerShell in `CONTRIBUTING.md` since running `bin/canonical_data_syncer` _should_ default to the `.ps1` varaint in PowerShell.

Alternatively you could merge this in and create an issue for this.

**Comment by Stargator** [comment]
@devkabiir I'll add it in a few hours to this PR

**Comment by Stargator** [comment]
@devkabiir I added it, but I cannot test it. I don't have Windows. If you can, could you make sure it's properly setup.

I don't know if we need to do anything to ensure it's executable.

**Review by devkabiir — APPROVED** [review]
For Windows, no executable flags have to be set, However PowerShell is now also available for Linux/Mac, so by using https://stackoverflow.com/a/40979016/6552940 it can be made convenient for those users as well.

On that thought, did you also set the bash version's executable flag?

**Comment by Stargator** [comment]
@devkabiir Yes

**Pull request merged**
