### PR TITLE
Revise Exercise READMEs using configlet generate command

### PR DESCRIPTION
**Pull request by Stargator**
Decided to run the `configlet generate` command on all the exercises and voila!

Most were missing a section on how to run tests. So included those updates here as well as added a README for raindrops which was apparently missing one.

### CODE REVIEW

**Comment by kabiir** [comment]
What if some of the Readmes already have content form problem specification and contributors have added more? Is that possibility covered.

**Comment by kabiir** [comment]
Did you manually update or actually used the configlet

**Comment by kabiir** [comment]
The changes if automated by the configlet are quite impressive.

**Comment by Stargator** [comment]
@kabiir I used the configlet generate command

**Comment by kabiir** [comment]
Usually I'd say **NO** to bulk changes but in this case it's fine. Should proceed with merge.

**Pull request merged**
