### PR TITLE
Delete file two_fer_test.dart

### PR DESCRIPTION
**Pull request by aly22**

### CODE REVIEW

**Comment by Stargator** [comment]
@aly22 What is the reasoning behind deleting this file?

I would think there is still value in having this practice exercise available to all users.

**Comment by aly22** [comment]
Updating your old code. Try running it.On Sat, 30 Jul 2022, 21:00 Stargator, ***@***.***> ***@***.*** What is the reasoning behind deleting this file?I would think there is still value in having this practice exercise available to all users.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by aly22** [comment]
Updated your old code.

**Comment by Stargator** [comment]
@aly22 Removing the required test file is not updating code, it'll result in the exercise no longer being functional for students. So I'm going to close this PR, unless you can provide a compelling reason.

**Pull request closed without merging**
