### PR TITLE
Add grains exercise

### PR DESCRIPTION
**Pull request by BNAndras**

### CODE REVIEW

**Comment by Stargator** [comment]
@ErikSchierboom, just checking are we accepting new exercises? Or is that a new track decision?

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom, just checking are we accepting new exercises? Or is that a new track decision?

I don't think so. The reason this PR wasn't auto-closed was that we have an expired token.

That said, the PR looks good. Are you happy to review or want me to do it?

**Comment by Stargator** [comment]
I'm fine with reviewing it.

**Review by Stargator — APPROVED** [review]

**Comment by Stargator** [comment]
Sorry for the delay in this review.

Please update with the latest version of grains, they changed some of the wording. Already approved and I will merge it when the update is made.

**Comment by BNAndras** [comment]
```
(base) ➜  exercism-dart git:(add-grains-exercise) ./bin/configlet sync --metadata --docs --filepaths --tests include -uye 
grains
Updating cached 'problem-specifications' data...
Checking exercises...
The `grains` exercise has up-to-date docs, filepaths, metadata, and tests!
```

**Pull request merged**
