### PR TITLE
Fix typos and update wording to common English in Dart track description

### PR DESCRIPTION
**Pull request by Cal-Hagner**
Replace "it's popularity" with "its popularity" and replace "amongst" (uncommon and antiquated English) with "in" (proper and common English).

### CODE REVIEW

**Comment by Cal-Hagner** [comment]
The CI is failing due to tests, as you are probably already aware. I changed a single Markdown file, so the CI shouldn't care.

**Comment by Stargator** [comment]
@Cal-Hagner Thanks for catching this and creating this PR despite the confusion you had in finding the correct repo.

Seems the test failures are due to dependencies and not any code written. Will have to check that in another issue.

**Comment by Stargator** [comment]
@iHiD @ErikSchierboom Could one of you trigger a rebuild? I went to Travis CI, but I can only trigger a build for a branch like master. I cannot get a rebuild of a PR.

**Comment by iHiD** [comment]
Closing/reopening seems to retrigger it so I've done that. If it hangs again let me know and I'll investigate further :)

**Pull request merged**
