### PR TITLE
exercism/dart: Add jvarness as a maintainer

### PR DESCRIPTION
**Pull request by Stargator**
* Also, correct pubspec.yaml with username change for kabiir to devkabiir

@jvarness has expressed interest in being a maintainer and seems to have a good grasp of the track's goals and intent.

### CODE REVIEW

**Comment by Stargator** [comment]
> @jvarness, Please provide your preferences for various maintainer fields such as show_on_website.

Additionally, whether you'd liked to list your email in the pubspec.yaml

**Comment by jvarness** [comment]
I'm comfortable with you guys listing my email address on the pubspec. Please use jake.varness@gmail.com.

As for the JSON, can you please set it to:

```json
{
  "github_username": "jvarness",
  "alumnus": false,
  "show_on_website": true,
  "name": Jake Varness,
  "link_text": "dev.to",
  "link_url": "https://dev.to/jvarness",
  "avatar_url": "https://avatars1.githubusercontent.com/u/6510879?s=460\u0026v=460",
  "bio": "Team Lead and Senior Software Engineer at Cerner Corporation, husband, father, nerd"
}
```

**Comment by Stargator** [comment]
Added the changes upon request, when I get home, I'll rebase them into one single commit.

**Comment by kytrinyx** [comment]
@Stargator In the future, when you are adding a maintainer, please email me directly at kytrinyx at exercism.io, as I need to explicitly add the new maintainer to the team. I get hundreds of email notifications from GitHub every day, and tagging me on a review is not a very reliable way of getting my attention.

**Comment by kytrinyx** [comment]
(I've invited @jvarness to the maintainer team)

**Comment by Stargator** [comment]
Sorry about that, I'll do that next time. I just haven't done it in almost a here.

**Comment by kytrinyx** [comment]
I've gotten the ball rolling to get our maintainer sync bot deployed, so next time it might be fine :)

I'll announce it in the https://github.com/orgs/exercism/teams/track-maintainers discussions when I get it working.

**Pull request merged**
