### PR TITLE
pubspec: Upgrade sdk constraints to Dart 3.2 as minimum

### PR DESCRIPTION
**Pull request by Stargator**
Upgrade our minimum SDK constraint to 3.2 (the latest version of Dart)

### CODE REVIEW

**Review by glennj — APPROVED** [review]
Excellent! Thanks for this.

**Comment by glennj** [comment]
Perhaps this too: https://github.com/exercism/dart/blob/42b0826e8ad2b949cbdd898433795730011522d6/.github/workflows/test.yml#L23

**Comment by glennj** [comment]
@vaeng, shall we coordinate this PR with a similar upgrade in exercism/dart-test-runner

**Comment by vaeng** [comment]
I don't know anything about dart compatibility, but I think my changes to the test runner would adapt easily to a new version. I'll do a pr today

**Comment by vaeng** [comment]
Okay, there is more changes. Error messages etc.
https://github.com/exercism/dart-test-runner/actions/runs/7765462161/job/21180134983?pr=76

**Comment by glennj** [comment]
@Stargator I see this 

> warning - bin/create_exercise.dart:295:38 - The operand can't be null, so the condition is always 'true'. Remove the condition. - unnecessary_null_comparison

https://github.com/exercism/dart/blob/42b0826e8ad2b949cbdd898433795730011522d6/bin/create_exercise.dart#L295

`retrieveListOfExpected()` returns a Set, so null-safe presumably.

**Comment by Stargator** [comment]
Yeah, I just made the pubspec changes on Friday and couldn't see the results of the checks until now. All should be resolved there.

**Comment by Stargator** [comment]
@glennj @vaeng , the checks all pass. Is there anything else or am I good to merge this?

**Comment by vaeng** [comment]
I did not change anything from the old 2.18 (?) Student files in the test runner, so this subset is still valid. I really never looked at any docs for dart except the test environment (which was not helpful for me). So if anything big has changed between the two versions, I'm the last to notice :D

**Comment by Stargator** [comment]
@vaeng I think you replying to my question in the dart-test-runner, but [the link to the changes is here](https://github.com/dart-lang/sdk/blob/3.0.0/CHANGELOG.md). As with any major version change, there are breaking changes. But so far, nothing broke in this PR when running the tests for the exercises, but that does not rule out students using other APIs that may have been deprecated or removed.

**Pull request merged**
