### PR TITLE
[phone-number]: Update Readme

### PR DESCRIPTION
**Pull request by rebelwarrior**
Fixes missing code brackets (typo).

### CODE REVIEW

**Comment by rebelwarrior** [comment]
changed subject

**Comment by rebelwarrior** [comment]
not sure how to change the commit comment from github. how do i do that?

**Comment by rebelwarrior** [comment]
maybe that did it

**Comment by devkabiir** [comment]
So you've already pushed your commit which means `git commit --amend` is not going to work.

What you can do now is do a soft reset e.g. `git reset ––soft HEAD~1` it will remove the last commit but still preserve your changes, now you can create a new commit using `git commit` and then you would have to do a force push using `git push <your-repo-remote> <your_branch_name> --force`.

But I think you've used the GitHub's web interface to make this change and submit the PR, so you wouldn't have a local copy of the repo correct?

In any case, it's fine as is it, I'll leave this PR open for now if you choose to play with git and make that change. I'll merge it in maybe a day or two.

P.S. While I was typing this you already made some changes so in this case you'd have to squash the commits you've made into a single commit for which you can use this command 
`git rebase -i 6e14fb9c07c7277caf449c95b499571f12d48078`. (This makes sure that you use the correct commit hash for squashing)

Here a great article on that https://gitbetter.substack.com/p/how-to-squash-git-commits

**Comment by rebelwarrior** [comment]
It’s easier to make a new pull request. I’ll do that.

**Pull request merged**
