### PR TITLE
remove WIP concept exercises from config.json: there is no WIP

### PR DESCRIPTION
**Pull request by glennj**
When concept exercises are actually in progress, this can be reinstated.

### CODE REVIEW

**Comment by Stargator** [comment]
> When concept exercises are actually in progress

It was my understanding that Exercism was working through the tracks to develop the concept exercises.

These, I believe, were the initial attempt but the guidance for concept exercises kept shifting.

I believe working on these are more important than implementing more exercises from the problem-specifications repo.

**Comment by glennj** [comment]
`configlet create` is useful for creating the exercise skeleton, so we don't need these anymore.

**Comment by glennj** [comment]
@Stargator any more thoughts on this? I agree that writing a syllabus is very high value, but nobody is doing it.

**Comment by Stargator** [comment]
@glennj, I have no issue with removing these. It doesn't look good on the website as they are incomplete.

**Review by Stargator — APPROVED** [review]

**Pull request merged**
