### PR TITLE
Fix numbering issue with Markdown as reported

### PR DESCRIPTION
**Pull request by Stargator**
As reported in #22, I am trying to provide a workaround.

Since it seems the code blocks are causing the issue I am going to try some alternatives

I will test these in a jekyll page since this seems to be related to red-carpet, we otherwise won't know how the webpage would turn out.

### CODE REVIEW

**Comment by Stargator** [comment]
No workaround currently found. Though I have noted a few issues.

In the Mac and Linux section, I made a typo and it goes  3,4,6 instead of 3,4,5.

Additionally, I changed the language used for Mac and Linux from batchfile to shell.

**Comment by Stargator** [comment]
@iHiD @kytrinyx 

[According to the Markdown syntax](https://daringfireball.net/projects/markdown/syntax#list), code blocks need to be double spaced. Kramdown is more forgiving in this case. But I have a solution and will create a pull request for java as well as look for any instances of this case in v1.

You can view the working example in [this branch of a example repo](https://github.com/Stargator/markdown-with-redcarpet/tree/red-double-space). Run `bundle install` and `bundle exec jekyll serve`. Assuming you have Ruby, Jekyll, and Bundler installed.

Screenshot as proof. Notice how Windows, which in this case is double indented, renders properly and macOS, which remain untouched, does not:

windows-vs-mac

**Comment by Stargator** [comment]
Issue stems from: https://github.com/exercism/v2-feedback/issues/105

**Comment by kytrinyx** [comment]
Thanks for digging into this.

The one thing I always do with markdown is use all the same number for numbered lists (usually 0 or 1). That way it should do the numbering by itself, and it's easy to insert new list items between existing items or reorder the items without having to edit the number itself.

If the indentation is correct, markdown _should_ handle the numbering automatically.

**Comment by Stargator** [comment]
@kytrinyx I'll make that change. I'll make all the numbers "1".

**Pull request merged**
